# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Google_Sigin_In' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google_Sigin_In

pod 'Firebase/Auth'

pod 'GoogleSignIn', '5.0.2'

end
