   # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase_DB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Database'
pod 'Kingfisher', '6.3.1'
pod 'lottie-ios', '3.2.3'

# pod 'Firebase/Firestore'
# pod 'FirebaseFirestoreSwift'


  # Pods for Firebase_DB

end
